title: Internship Management System
description: English documentation (requirements, design, testing) for MFU students
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
